version: '3.8'

services:
  redis:
    image: redis:7.2.3
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    networks:
      - codemakerlab
    volumes:
      - redis_data:/data

  postgres_db:
    image: postgres:15.5
    container_name: postgres_db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: Account
    depends_on:
      - redis
    ports:
      - 5432:5432
    restart: always
    networks:
      - codemakerlab
    volumes:
      - local_pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on:
      - postgres_db
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 80:80
    networks:
      - codemakerlab
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  # mariadb:
  #   image: mariadb:11.2
  #   container_name: mariadb
  #   restart: always
  #   env_file:
  #     - .env
  #   environment:
  #     MARIADB_USER: admin
  #     MARIADB_PASSWORD: admin
  #     MARIADB_ROOT_PASSWORD: admin
  #   ports:
  #     - 3305:3306
  #   networks:
  #     - codemakerlab
  #   volumes:
  #     - local_mariadb_data:/var/lib/mysql:Z

  # phpmyadmin:
  #   image: phpmyadmin:5.2
  #   container_name: phpmyadmin
  #   environment:
  #     - PMA_ARBITRARY=1
  #   depends_on:
  #     - mariadb
  #   restart: always
  #   ports:
  #     - 80:80
  #   networks:
  #     - codemakerlab

networks:
  codemakerlab:

volumes:
  local_pgdata:
  pgadmin_data:
  redis_data:
  # local_mariadb_data:
  # phpmyadmin_data: